
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from time import sleep
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from Windows.Main import *
from Windows.Home import Home


def main():
    window = Tk()
    app = Home(window)
    window.resizable(False, False)
    window.mainloop()


if __name__ == "__main__":
    main()
