
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x620")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 620,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1000.0,
    620.0,
    fill="#EAABF4",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=22.0,
    y=202.0,
    width=240.0,
    height=60.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=22.0,
    y=428.0,
    width=240.0,
    height=60.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=22.0,
    y=317.0,
    width=240.0,
    height=60.0
)

canvas.create_rectangle(
    337.0,
    81.0,
    976.0,
    571.0,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    525.0,
    253.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    656.5,
    453.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    highlightthickness=0
)
entry_1.place(
    x=434.5,
    y=419.0,
    width=444.0,
    height=67.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=620.0,
    y=506.0,
    width=97.0,
    height=46.0
)

canvas.create_rectangle(
    683.0,
    271.0,
    913.0,
    372.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    683.0,
    271.0,
    913.0,
    372.0,
    fill="#8753B8",
    outline="")

canvas.create_text(
    687.0,
    277.0,
    anchor="nw",
    text="Dont worry about\n the Prinzessin, she\njust works here",
    fill="#000000",
    font=("Inter", 23 * -1)
)

canvas.create_text(
    6.0,
    38.0,
    anchor="nw",
    text="AniCrawler",
    fill="#000000",
    font=("Inter", 40 * -1)
)

canvas.create_rectangle(
    296.5,
    -2.0,
    298.5,
    620.0007934570312,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -5.0,
    83.0,
    155.0,
    88.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
